### ISSUE TITLE
some actual docs would be great :)

### ISSUE THREAD

**Issue by blissdev** [DavidDurman/statechart#1]
I have been looking into js state machines and saw this on FunctionSource. Would like to encourage you to develop it further. Docs = win.

**Comment by gregwebs** [comment]
This test case probably gives you most of the docs you need: https://github.com/DavidDurman/statechart/blob/master/test/samek.js

I created an alternative statechart library: https://github.com/yaptv/StateTree

**Comment by DavidDurman** [comment]
Nice work! I see you are following a different philosophy and an OO approach. My work is based on QHsm (Quantum Hierarchical State machines) developed by Miro Samek (google for details, slides can be found e.g. here: http://www.accu-usa.org/slides/samek0311.pdf). I wish I could find some time to develop this library further.... and add some docs.

**Comment by DavidDurman** [comment]
Just added some basic documentation to README. I'll try to write a blog post in the near future.

**Comment by gregwebs** [comment]
@blissdev there are diagrams & examples, should this be closed now?

**Comment by blissdev** [comment]
@gregwebs Yes, I'm excited to see the progress. Thanks for the effort.  /cc @DavidDurman
