### ISSUE TITLE
Harel's statechart formalism

### ISSUE THREAD

**Issue by brucou** [DavidDurman/statechart#18]
While reviewing the library, I was wondering whether you have the following features from Harel's statechart formalism: 

- concurrency (or parallel) states
- history (shallow or else) navigation

I could not figure that out from Quantum Leaps web pages.

Thanks

**Comment by EasonPai** [comment]
I have the same question

**Comment by brucou** [comment]
From the source code, it seems the answer is no to both questions.

**Comment by gregwebs** [comment]
These both exist in the JS statechart lib that I wrote: https://github.com/gregwebs/StateTree

**Comment by brucou** [comment]
@gregwebs you should join this group : https://spectrum.chat/statecharts dedicated to state charts and let people know.
