### ISSUE TITLE
Add statechart to Bower

### ISSUE THREAD

**Issue by thomaspons** [DavidDurman/statechart#3]
Is it possible to add statechart to Bower repository ?

It could be really helpful for us and for all the community IMHO :+1: 

Thanks, 

Thomas Pons

**Comment by DavidDurman** [comment]
Just did that. `bower install statechart` should do the job. Could you please verify if everything's ok as my experience with bower is quite limited. Thanks!

**Comment by thomaspons** [comment]
It works ;-) ! Really nice job ! Thanks
